const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.right
	];
};
self.C3_JsPropNameTable = [
	{LocalStorage: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{Anchor: 0},
	{Game_Tittle: 0},
	{show: 0},
	{ScrollTo: 0},
	{men_manager: 0},
	{bgMainMenu: 0},
	{bgMainMenuDown: 0},
	{paused: 0},
	{win: 0},
	{defeat: 0},
	{itemSelected: 0},
	{destroyLine1: 0},
	{destroyLine2: 0},
	{destroyLine3: 0},
	{destroyLine4: 0},
	{destroyLine5: 0},
	{goal1: 0},
	{goal2: 0},
	{goal3: 0},
	{time: 0},
	{color1: 0},
	{color2: 0},
	{color3: 0},
	{color4: 0},
	{color5: 0},
	{color6: 0},
	{falling: 0},
	{gamemanager: 0},
	{bgGame: 0},
	{lines: 0},
	{basescore: 0},
	{basetime: 0},
	{line: 0},
	{nIndex: 0},
	{selected: 0},
	{nColumn: 0},
	{nRow: 0},
	{isMatched: 0},
	{moveCantPos: 0},
	{Tween: 0},
	{Sine: 0},
	{monster: 0},
	{Nivel: 0},
	{btnNivel: 0},
	{star_selector: 0},
	{star_selector_nivel: 0},
	{nHoja: 0},
	{dragging: 0},
	{topLimit: 0},
	{startX: 0},
	{Bullet: 0},
	{cam_selector: 0},
	{txtBtnNivel: 0},
	{name: 0},
	{txtUI: 0},
	{Fade: 0},
	{txtInGame: 0},
	{Variables: 0},
	{MonsterAnimations: 0},
	{btnCredits: 0},
	{btnMoreGames: 0},
	{btnPlay: 0},
	{btnRight: 0},
	{btnLeft: 0},
	{btnBack: 0},
	{btnMenuSelector: 0},
	{btnPausa: 0},
	{btnCont: 0},
	{btnMenu: 0},
	{btnReset: 0},
	{btnSound: 0},
	{QkyGamesLogo: 0},
	{bgCredits: 0},
	{bgWin: 0},
	{star_win: 0},
	{emiter: 0},
	{fadeSubMenu: 0},
	{black_fade: 0},
	{Rotate: 0},
	{monster_particles: 0},
	{bgDefeat: 0},
	{basebar: 0},
	{characters: 0},
	{fill_barr: 0},
	{bgGoal: 0},
	{nTuto: 0},
	{bgTuto: 0},
	{pagerbase: 0},
	{tutorial: 0},
	{bgPause: 0},
	{bg: 0},
	{bgUI: 0},
	{marcador: 0},
	{Botones: 0},
	{SineElements: 0},
	{MonstersF: 0},
	{totStars: 0},
	{totScore: 0},
	{lastBg: 0},
	{star: 0},
	{sizeCellPlayer: 0},
	{score: 0},
	{Level: 0},
	{cant: 0},
	{posX: 0},
	{posY: 0},
	{nColor: 0},
	{mag: 0},
	{tiempo: 0},
	{cantEnemies: 0},
	{anim: 0},
	{nDestroy: 0},
	{baseScore: 0},
	{Loading: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{layer: 0},
	{cantidad: 0},
	{txt: 0},
	{gametime: 0},
	{milliseconds: 0},
	{seconds: 0},
	{minutes: 0},
	{timeractive: 0},
	{tiempoacalcular: 0}
];

self.InstanceType = {
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Game_Tittle: class extends self.ISpriteInstance {},
	men_manager: class extends self.ISpriteInstance {},
	bgMainMenu: class extends self.IWorldInstance {},
	bgMainMenuDown: class extends self.IWorldInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	bgGame: class extends self.IWorldInstance {},
	lines: class extends self.IWorldInstance {},
	basescore: class extends self.ISpriteInstance {},
	basetime: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	monster: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	star_selector: class extends self.ISpriteInstance {},
	star_selector_nivel: class extends self.ISpriteInstance {},
	cam_selector: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	txtInGame: class extends self.ISpriteFontInstance {},
	Variables: class extends self.IArrayInstance {},
	MonsterAnimations: class extends self.IArrayInstance {},
	btnCredits: class extends self.ISpriteInstance {},
	btnMoreGames: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	btnLeft: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnMenuSelector: class extends self.ISpriteInstance {},
	btnPausa: class extends self.ISpriteInstance {},
	btnCont: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	QkyGamesLogo: class extends self.ISpriteInstance {},
	bgCredits: class extends self.ISpriteInstance {},
	bgWin: class extends self.ISpriteInstance {},
	star_win: class extends self.ISpriteInstance {},
	emiter: class extends self.ISpriteInstance {},
	fadeSubMenu: class extends self.ISpriteInstance {},
	black_fade: class extends self.ISpriteInstance {},
	monster_particles: class extends self.ISpriteInstance {},
	bgDefeat: class extends self.ISpriteInstance {},
	basebar: class extends self.ISpriteInstance {},
	characters: class extends self.ISpriteInstance {},
	fill_barr: class extends self.ITiledBackgroundInstance {},
	bgGoal: class extends self.ISpriteInstance {},
	bgTuto: class extends self.ISpriteInstance {},
	pagerbase: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	bgPause: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	bgUI: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	Botones: class extends self.ISpriteInstance {},
	SineElements: class extends self.ISpriteInstance {},
	MonstersF: class extends self.ISpriteInstance {}
}